### ISSUE TITLE
ValueError when training

### ISSUE THREAD

**Issue by manelbenaissa** [datamade/parserator#42]
Hello

I'm trying to create a module similar to usaddress but for another country so I had to set up new labels. I made a labeled xml file with those labels. However when I try the parserator train command line i get  this error : 

Traceback (most recent call last):
  File "/home/n1a/.local/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/home/n1a/.local/lib/python2.7/site-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/home/n1a/.local/lib/python2.7/site-packages/parserator/main.py", line 66, in train
    training.train(module, train_file_list)
  File "/home/n1a/.local/lib/python2.7/site-packages/parserator/training.py", line 92, in train
    trainModel(training_data, module)
  File "/home/n1a/.local/lib/python2.7/site-packages/parserator/training.py", line 31, in trainModel
    trainer.append(xseq, yseq)
  File "pycrfsuite/_pycrfsuite.pyx", line 312, in pycrfsuite._pycrfsuite.BaseTrainer.append
ValueError: The numbers of items and labels differ: |x| = 1, |y| = 13

I am using python 2.7

**Comment by jeancochrane** [comment]
Hey @manelbenaissa,

My guess is that your labeled file is malformed in some way. Mind sharing your XML file so we can see if it's valid?

**Comment by manelbenaissa** [comment]
Hello, managed to correct the problem finally it was a problem in my __init__.py file
