### ISSUE TITLE
TypeError: 'write() argument 1 must be unicode, not str'

### ISSUE THREAD

**Issue by joeribelis** [datamade/parserator#49]
python 2.7

:~/parser$ parserator init test_123

Initializing directories for test_123 <open file '<stderr>', mode 'w' at 0x7f98203211e0>
* test_123 <open file '<stderr>', mode 'w' at 0x7f98203211e0>
* raw <open file '<stderr>', mode 'w' at 0x7f98203211e0>
* training <open file '<stderr>', mode 'w' at 0x7f98203211e0>
* tests <open file '<stderr>', mode 'w' at 0x7f98203211e0>

Generating __init__.py <open file '<stderr>', mode 'w' at 0x7f98203211e0>
Traceback (most recent call last):
  File "/home/joerib/.local/bin/parserator", line 8, in <module>
    sys.exit(dispatch())
  File "/home/joerib/.local/lib/python2.7/site-packages/parserator/main.py", line 70, in dispatch
    args.func(args)
  File "/home/joerib/.local/lib/python2.7/site-packages/parserator/main.py", line 118, in init
    f.write(parser_template.init_template())
TypeError: write() argument 1 must be unicode, not str

**Comment by joeribelis** [comment]
replacing "w" with "wb"
https://stackoverflow.com/questions/45520097/wb-vs-w-in-unix-for-python

seems to fix it
