### ISSUE TITLE
Use subcommands for parserators

### ISSUE THREAD

**Issue by fgregg** [datamade/parserator#5]
Let's use sub-commands for parserators: https://docs.python.org/2/library/argparse.html#sub-commands

Something like

```bash
> parserator
usage: parserator {label, train} ...

positional arguments:
  {label, train}
> parserator label
usage: parserator label infile outfile modulename

parserator update: error: the following arguments are required: infile, outfile, module
> parserator train
usage: parserator training_file modulename
parserator trail: error the following arguments are required: training_file modulename
```

**Comment by fgregg** [comment]
Getting this error message:

```bash
11:52 AM|fgregg-ThinkPad-X201|~/public/name-parser>parserator label train.csv name_data/labeled/manually_labeled.xml name_parser/
Traceback (most recent call last):
  File "/usr/local/bin/parserator", line 9, in <module>
    load_entry_point('parserator==0.1', 'console_scripts', 'parserator')()
  File "/home/fgregg/public/parserator/parserator/main.py", line 32, in dispatch
    args.func(args)
  File "/home/fgregg/public/parserator/parserator/main.py", line 37, in label
    module = __import__(args.modulename)
ImportError: Import by filename is not supported.
```

**Comment by fgregg** [comment]
Getting this error message:

```bash
11:54 AM|fgregg-ThinkPad-X201|~/public/name-parser>parserator label train.csv name_data/labeled/manually_labeled.xml name_parser
/home/fgregg/public/parserator/parserator/manual_labeling.py:191: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  strings = set([unidecode.unidecode(row[0]) for row in reader])

Start console labeling!

These are the tags available for labeling:
0 : PrefixMarital
1 : PrefixOther
2 : GivenName
3 : FirstInitial
4 : MiddleName
5 : MiddleInitial
6 : Surname
7 : LastInitial
8 : SuffixGenerational
9 : SuffixOther
10 : Nickname
11 : And



(1 of 1)
--------------------------------------------------
STRING: Rahm Emanuel
/home/fgregg/public/name-parser/name_parser/__init__.py:49: UserWarning: You must train the model (parserator train --trainfile FILES) to create the learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train --trainfile FILES) to create the %s file before you can use the parse and tag methods' %MODEL_FILE)
Segmentation fault (core dumped)
```

**Comment by fgregg** [comment]
parserator label train.csv name_data/labeled/manually_labeled.xml name_parser
/home/fgregg/public/parserator/parserator/manual_labeling.py:191: RuntimeWarning: Argument <type 'str'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  strings = set([unidecode.unidecode(row[0]) for row in reader])

Start console labeling!

These are the tags available for labeling:
0 : PrefixMarital
1 : PrefixOther
2 : GivenName
3 : FirstInitial
4 : MiddleName
5 : MiddleInitial
6 : Surname
7 : LastInitial
8 : SuffixGenerational
9 : SuffixOther
10 : Nickname
11 : And



(1 of 1)
--------------------------------------------------
STRING: Rahm Emanuel
/home/fgregg/public/name-parser/name_parser/__init__.py:49: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' %MODEL_FILE)
Segmentation fault (core dumped)

**Comment by fgregg** [comment]
Cool, thansk!
